In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('/content/salaries.csv')
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025,SE,FT,Data Product Owner,170000,USD,170000,US,0,US,M
1,2025,SE,FT,Data Product Owner,110000,USD,110000,US,0,US,M
2,2025,SE,FT,Data Product Owner,170000,USD,170000,US,0,US,M
3,2025,SE,FT,Data Product Owner,110000,USD,110000,US,0,US,M
4,2025,SE,FT,Engineer,143000,USD,143000,US,0,US,M
...,...,...,...,...,...,...,...,...,...,...,...
73143,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
73144,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
73145,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
73146,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
73147,2021,SE,FT,Data Scientist,7000000,INR,94665,IN,50,IN,L

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73148 entries, 0 to 73147
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           73148 non-null  int64
 1   experience_level    73148 non-null  object
 2   employment_type     73148 non-null  object
 3   job_title           73148 non-null  object
 4   salary              73148 non-null  int64
 5   salary_currency     73148 non-null  object
 6   salary_in_usd       73148 non-null  int64
 7   employee_residence  73148 non-null  object
 8   remote_ratio        73148 non-null  int64
 9   company_location    73148 non-null  object
 10  company_size        73148 non-null  object
dtypes: int64(4), object(7)
memory usage: 6.1+ MB

In [4]:
df.shape

(73148, 11)

In [5]:
df.describe()

          work_year        salary  salary_in_usd  remote_ratio
count  73148.000000  7.314800e+04   73148.000000  73148.000000
mean    2023.831192  1.625534e+05  158013.748619     21.582955
std        0.477551  1.925761e+05   72501.304728     41.023051
min     2020.000000  1.400000e+04   15000.000000      0.000000
25%     2024.000000  1.069575e+05  106890.000000      0.000000
50%     2024.000000  1.480000e+05  147500.000000      0.000000
75%     2024.000000  2.000000e+05  199700.000000      0.000000
max     2025.000000  3.040000e+07  800000.000000    100.000000

In [9]:
df.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [12]:
## Q1.How many unique job titles are there?
df['job_title'].nunique()

289

In [14]:
##Q2. what are the difference level in this dataset?
df['experience_level'].unique()

array(['SE', 'EN', 'MI', 'EX'], dtype=object)

In [15]:
## Q3. what are the difference employment type?
df['employment_type'].unique()

array(['FT', 'PT', 'CT', 'FL'], dtype=object)

In [17]:
## Q4.What currencies are used in the dataset?
df['salary_currency'].unique()

array(['USD', 'GBP', 'EUR', 'PHP', 'CAD', 'SGD', 'BRL', 'INR', 'PLN',
       'CHF', 'AUD', 'JPY', 'DKK', 'CZK', 'HUF', 'MXN', 'ILS', 'TRY',
       'ZAR', 'SEK', 'NZD', 'NOK', 'HKD', 'THB', 'CLP'], dtype=object)

In [18]:
##Q5. What is the most common job title?
df['job_title'].value_counts().idxmax()

'Data Scientist'

In [19]:
##Q6. Which job title has the highest average salary?
df.groupby('job_title')['salary_in_usd'].mean().idxmax()

'Analytics Engineering Manager'

In [20]:
##Q7.What is the minimum salary (in USD)?
df.salary_in_usd.min()

15000

In [21]:
## Q8. what are the maximum salary(in USD)?
df.salary_in_usd.max()

800000

In [22]:
##Q9. What is the average salary (in USD)?
df.salary_in_usd.mean()

np.float64(158013.7486192377)

In [24]:
##Q10.How many people work 100% remotely?
df[df['remote_ratio']== 100].shape[0]

15647

In [25]:
##Q11. how many people work 0% remotely?
df[df['remote_ratio']== 0].shape[0]

57220

In [27]:
## Q12. how many people work 50% remotely?
df[df['remote_ratio']== 50].shape[0]

281

In [29]:
##Q13.what is the common company size
df['company_size'].value_counts().idxmax()

'M'

In [33]:
##Q14.How many employees are in large companies?
df[df['company_size']== 'L'].shape[0]

2407

In [34]:
##Q15.How many employees are in small companies?
df[df['company_size']== 'S'].shape[0]

205

In [35]:
##Q16. Which salary currency appears most frequently?
df['salary_currency'].value_counts().idxmax()

'USD'

In [37]:
##Q17.How many total entries are in the dataset?
df.shape[0]

73148

In [40]:
##Q18. What is the average salary for Senior-level (SE) employees?
df[df['experience_level'] == 'SE']['salary_in_usd'].mean()

np.float64(173297.81298047802)

In [41]:
##Q19.Which employment type has the highest average salary?
df.groupby('employment_type')['salary_in_usd'].mean().idxmax()

'FT'

In [42]:
##Q20. Which three countries have the most employees residing there?
df['employee_residence'].value_counts().head(3)

employee_residence
US    65982
CA     2513
GB     2127
Name: count, dtype: int64

In [43]:
##Q21. Which five countries have the most employees residing there?
df['employee_residence'].value_counts().head(5)

employee_residence
US    65982
CA     2513
GB     2127
AU      238
DE      222
Name: count, dtype: int64

In [44]:
##Q22. Whichcountries have the maxemployees residing there?
df['employee_residence'].value_counts().idxmax()

'US'

In [45]:
##Q23. Whichcountries have the min employees residing there?
df['employee_residence'].value_counts().idxmin()

'RW'